### ISSUE TITLE
API Contributor Key Can't Be Used To Append

### ISSUE THREAD

**Issue by tylerpuleo** [isenseDev/rSENSE#1932] opened 2015-01-22 21:21 UTC
General description: When using API to append there is a function on the API that says it can append to the API with a contributor key but the server log says that the request is unauthorized.

live/dev/localhost: dev
iSENSE Version: v5.8
Logged in (Y or N): Y
Admin (Y or N): N

OS: Ubuntu 14.04
Browser/Version: Chrome 37.0.2062.120

Steps to Reproduce: Make an append post request to the API using a contributor key.

**Comment by JasonD94** [comment] 2015-01-22 23:40
I had issues with this as well in C++. I was able to get appending to work with the email/password API but contributor keys always gave a  "Contribution key not valid" error (status 401).

**Comment by fgmart** [comment] 2015-01-22 23:52
Please give fixing this high priority.

**Comment by kcarcia** [comment] 2015-01-23 00:23
@bdonald25 this is currently the highest priority bug assigned to you.

**Comment by bdonald25** [comment] 2015-01-23 01:58
The way it works now is it lets you append data to data sets that were uploaded with the same key. 

Just to clarify we want to be able to append data to any data set in a project with a key instead of just the ones uploaded with that key?

**Comment by fgmart** [comment] 2015-01-23 02:03
Oh. That behavior as you describe it @bdonald25 seems correct.

@JasonD94 @tylerpuleo -- would you please confirm this.

All -- is there documentation for this? There should be. Please point me at it?

**Comment by bdonald25** [comment] 2015-01-23 02:07
http://isenseproject.org/api/v1/docs
The documentation doesn't clarify this so I could make a note there.

**Comment by fgmart** [comment] 2015-01-23 02:14
OK... that is super terse docs... how hard is it to add a bit of narrative
to this?  definitely add this bit. Thanks.

On Thu, Jan 22, 2015 at 9:07 PM, Bobby Donald <notifications@github.com>
wrote:

> http://isenseproject.org/api/v1/docs
> <https://urldefense.proofpoint.com/v2/url?u=http-3A__isenseproject.org_api_v1_docs&d=AwMCaQ&c=TqceLeU8_c9CVUat-eLTFu19-lyGiWSvB_skZXlxt8Q&r=18cCOnjUNVJkR7XAgiboog&m=DEx4fu5_nHV__IsqPfSDFrSQ-AaawR9HQOtpXGpSLYA&s=Pc9C9lkEAUY33qFRyi9uxH2RAqn5PU3zSsAP52BwaAg&e=>
> The documentation doesn't clarify this so I could make a note there.
>
> —
> Reply to this email directly or view it on GitHub
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_isenseDev_rSENSE_issues_1932-23issuecomment-2D71136465&d=AwMCaQ&c=TqceLeU8_c9CVUat-eLTFu19-lyGiWSvB_skZXlxt8Q&r=18cCOnjUNVJkR7XAgiboog&m=DEx4fu5_nHV__IsqPfSDFrSQ-AaawR9HQOtpXGpSLYA&s=8ZE61gbJtNyX2iuPjTPpGD5qCAfN604Od5MlyhbNRRc&e=>
> .
>



-- 

Work Ready Life Ready World Ready

Director, Engaging Computing Group <http://www.cs.uml.edu/ecg>
Associate Professor, Computer Science <http://blog.uml.edu/cs>
Director of Student Success, College of Sciences
<http://blog.uml.edu/science>
University of Massachusetts Lowell, 1 University Avenue, Lowell MA 01854
p: 978/934–1964 f: 978/934–2705 email: fredm@cs.uml.edu

**Comment by JasonD94** [comment] 2015-01-23 02:18
So if you upload with an email and password, and then try to append with a contributor key, it would not work?
If that's so, that could explain why I couldn't append with the key but it worked with email / password.

**Comment by fgmart** [comment] 2015-01-23 02:22
So an API key will let you create a new data set -- which is then owned by the project owner.

That same key will let you append to that data set.

It seems correct to me that if the data set were created by uname/pwd, then the API key won't work on it.

@jdalphon this is exactly as intended, yes?

**Comment by tylerpuleo** [comment] 2015-01-23 15:01
I apologize, I just realized that iSENSE saw the dataset that I was trying
to post to as being posted via username and password. I tried appending
using a dataset that iSENSE saw as a contributor key post and it worked.

However, I am almost certain that I posted the dataset that didn't work
with a contributor key and iSENSE processed it as email/password. I will
investigate this further and see what I find.

-Tyler

**Comment by JasonD94** [comment] 2015-01-23 17:32
I just tried appending to a dataset uploaded with a key and I'm still getting the same "key not valid" error.

Project I tried: http://rsense-dev.cs.uml.edu/projects/1029
(I just created a new project to test this one)
Contributor key is "123". 

I tried sending a POST to: http://rsense-dev.cs.uml.edu/api/v1/data_sets/append
With the following JSON data:
{"contribution_key":"123","data":{"4566":[456]},"id":"7742","title":"test"}

And I get the following error:
{ "msg": "Contribution key not valid"}
With an HTTP code of 401 Unauthorized.

**Comment by bdonald25** [comment] 2015-01-23 17:37
Really? I was able to do it yesterday. I'll send you my code in a bit.

**Comment by bdonald25** [comment] 2015-01-23 18:22
function post() {
    
    var apiUrl = 'http://rsense-dev.cs.uml.edu/api/v1/data_sets/append';
    var upload = {

        'contribution_key':'key',
        'id':'7753',
        'data':
        {
        	'4581' : [11, 22, 33],
            '4582': [11, 22, 33]
        }
    }
    $.post(apiUrl, upload);
    alert("Post Successful");
}

**Comment by bdonald25** [comment] 2015-01-23 18:22
You can see the data was appended here. http://rsense-dev.cs.uml.edu/projects/1033/data_sets/7753

**Comment by bdonald25** [comment] 2015-01-23 18:23
<!DOCTYPE html>
<html>
    <head>
        <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
        <script src="postNotWorking.js"></script>
    </head>
    <body>
        <button onclick="post();">POST</button>
    </body>
</html>

Here is the html I used if you want to test it yourself.

**Comment by JasonD94** [comment] 2015-01-23 18:26
Thanks!

Is there a reason why you left out the title? On the API docs it lists that as required.

This is what the API docs gives as an example:
```
  {
    "contribution_key" => "a contribution key (string)",
    "title" => "A title for the data set (string)"
    "id" => "dataset id (integer)"
    "data" =>
      {
        "FIELD_ID" => [1,2,3,4,5],
        "FIELD_ID_2" => ["blue","red",,,"green"]
      }
  }
```

**Comment by bdonald25** [comment] 2015-01-23 18:31
I think someone put it there as a mistake. It doesn't make sense to have a title because the data set already exists. I was looking at the api and I didn't see the title being referenced anywhere. However, it should still work if you leave it in. 

Maybe the intent was to allow people to change the title?

**Comment by tylerpuleo** [comment] 2015-01-23 19:48
Ya I noticed that the title didn't do anything.

**Comment by fgmart** [comment] 2015-01-23 20:08
OK Tyler you're still verifying whether it may work if you don't include
title?

On Fri, Jan 23, 2015 at 2:48 PM, tylerpuleo <notifications@github.com>
wrote:

> Ya I noticed that the title didn't do anything.
>
> On Fri, Jan 23, 2015, 1:31 PM Bobby Donald <notifications@github.com>
> wrote:
>
> > I think someone put it there as a mistake. It doesn't make sense to have
> a
> > title because the data set already exists. I was looking at the api and
> I
> > didn't see the title being referenced anywhere. However, it should still
> > work if you leave it in.
> >
> > Maybe the intent was to allow people to change the title?
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/isenseDev/rSENSE/issues/1932#issuecomment-71240406>.
>
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_isenseDev_rSENSE_issues_1932-23issuecomment-2D71253705&d=AwMFaQ&c=TqceLeU8_c9CVUat-eLTFu19-lyGiWSvB_skZXlxt8Q&r=18cCOnjUNVJkR7XAgiboog&m=RoV7tArAtcrbhtn8q607M_rBL5ny6KohANjcmMRzZAE&s=Dy4tfxcd3AVvbX6ipRavjlSO2uQY7nm-TSnmW3GLMgY&e=>
> .
>



-- 

Work Ready Life Ready World Ready

Director, Engaging Computing Group <http://www.cs.uml.edu/ecg>
Associate Professor, Computer Science <http://blog.uml.edu/cs>
Director of Student Success, College of Sciences
<http://blog.uml.edu/science>
University of Massachusetts Lowell, 1 University Avenue, Lowell MA 01854
p: 978/934–1964 f: 978/934–2705 email: fredm@cs.uml.edu

**Comment by bdonald25** [comment] 2015-01-23 20:13
I tried it with and without the title and it worked both ways for me. 
Title appears to have been put into the api docs by mistake.

**Comment by bdonald25** [comment] 2015-01-23 20:34
I do think it is weird that a key can only append to a dataset uploaded with the same key, but a username and password can append anyone's dataset. Is this what we want?

**Comment by tylerpuleo** [comment] 2015-01-23 22:29
I can confirm that it works fine when the title is included, but it doesn't
change anything.

I have not tried omitting the title.

-Tyler

**Comment by jaypoulz** [comment] 2015-01-24 00:19
Ownership of data sets uploaded with contributor keys are at a per-key basis. This means that you should only be able to append to a data set that your key uploaded. 

Ownership of data sets uploaded via username and password are at a per-user basis, which can be much more complicated. 
- [ ] You should be able to append to any dataset if you're an admin.
- [ ] You should be able to appended data set you own 
- [ ] In any PROJECT you own, you should be able to append to you own OR any data set uploaded by key (these are also the data sets you have 'edit' permission over)

**Comment by bdonald25** [comment] 2015-01-26 18:20
@jaypoulz is going to add documentation that clearly explains who can append which data sets.

**Closed by bdonald25** 2015-01-26 18:20 UTC
Labels: API Change, Bug, High Priority
