### ISSUE TITLE
Mike's Home Page Feedback

### ISSUE THREAD

**Issue by stowellm** [isenseDev/rSENSE#1975] opened 2015-02-03 18:59 UTC
**General description:**
- [x] Rather than scale-to-fit on the top images on the homepage, I think a fill would be more appropriate (i.e. image takes on the larger of either width or height and extends beyond the bounds of the other)
- [x] I really don't like how the iSENSE menubar is non-static.  This could be debatable and affects the whole website, but I think it should always remain up top even when scrolling (just wanted to mention it somewhere)
- [x] Titles may look better in all caps (with exception to the lowercase 'i' in "iSENSE" perhaps?  Worth playing with.  See screenshot 1 below.
- [x] The text cards don't pop - they're just plain gray.  Maybe a border or little art piece would make it stand out more?  Again, see screenshot 1 below (art in the bottom right of the boxes)
- [x] I'm assuming the .png of a histogram is just a placeholder for an embedded vis
- [x] The description for mobile apps on the Apple App Store is misleading - should mention that they aren't available but will be soon
- [x] The "Read More" piece in the news should have a greater height - I like the blur, but not when it's that small (see second screenshot, circle labeled "A")
- [x] Images in news should not be left-aligned: it causes the image to be cut off awkwardly. Again, would recommend a fill approach here instead (second screenshot, circle labeled "B")
- [x] The words "Collect," "Share," and "Visualize" should be bolded in the "What is iSENSE?" box
- [x] The "Collect Share Visualize" on the bottom of the home page should use the same colors as the "Collect Share Visualize" in the "What is iSENSE?" box
- [x] The "Get Involved with iSENSE" box should also link to the contact page for further contact info
- [x] The statistics should list "Users - Projects - Data Sets" in that order instead of the order it is now (Users - Data Sets - Projects).  Think of the order you create things: you sign up as a user first, then you create a project, then you contribute data sets
- [x] Over the main images on the top of the homepage, should there be a button or something of the like hovering over that says "Learn More" that autoscrolls the user down past the images to the "What is iSENSE?" content?  This may help show the user there is more content to this homepage rather than relying on them to scroll to it
- [x] "Teachers love iSENSE" content text is bold and "What is iSENSE"  content text isn't.  Seems inconsistent.
- [x] Shrinking the browser window to mobile-size makes the statistics disappear - is this intentional?

---

If this feedback is better suited as a comment somewhere else, let me know and I'll move it.

---

**live/dev/localhost:** dev
**iSENSE Version:** v5.12-308-g7ba736c
**Logged in (Y or N):** N
**Admin (Y or N):** N

**OS:** Windows 8.1
**Browser/Version:** Chrome 40.0

**Steps to Reproduce:** n/a

**Associated Image(s):**
Screenshot example from RedHat's homepage
![red_hat_sample](https://cloud.githubusercontent.com/assets/1039162/6026783/6bb96830-abab-11e4-8ae3-2dfb8b68e4ba.png)

Screenshot of the rSENSE homepage
![isense_sample](https://cloud.githubusercontent.com/assets/1039162/6026855/0280e0fe-abac-11e4-922a-d78224b3d81c.png)

**Comment by JKinsman** [comment] 2015-02-04 15:15
Thank you very much for the feedback, @stowellm !

1.  I agree, this will definitely be fixed.
2.  I did not plan to fix this, although it can definitely be open to discussion.  Personally, I'm against it.  Sorry! :stuck_out_tongue:
3.  I agree, this will be fixed
4.  This was initially by design, but is also preference.  I will find something subtle that I can add to make them stand out a bit more.
5.  Currently, it is not.  There was a bit of discussion regarding whether the homepage should contain an embedded vis.  I think we ultimately decided against it in favor or simplicity and maintenance, although if people want an embedded vis, this is definitely something I would be happy to consider.  
6.  I will adjust the text to reflect that the iOS apps are coming soon.
7-10.  Agreed!  I will fix these :smile: 
11.  We originally decided against this, given that the link is on the bottom, although truthfully, I like the idea.  If it seems reasonable, I will add it.
12.  100% agree! :smile: 
13.  I previously implemented something to "guide" the user through the page.  It was decided to abandon this in favor of allowing the user to freely explore the page, but with gentle "guidance".  I feel as though this is stepping in the opposite direction.  I won't be implementing this, as I'm afraid you're definitely in the minority on this one.  Sorry Mike! :disappointed: 
14.  Will fix!
15.  Yes, this is intended behavior.  The Stats information did not seem critical enough to make the mobile view.  As the screen size is inherently smaller, we decided to limit the mobile view to only contain the most important content.


Thank you very much for all the feedback, Mike!  You're the best! :smile:

**Comment by JKinsman** [comment] 2015-02-04 15:24
@stowellm I just tried capitalizing the titles.  I think it looked better previously.

**Comment by JKinsman** [comment] 2015-02-04 22:21
@stowellm I believe I have addressed all the concerns I checked above.  Check Dev, and let me know if you have any additional concerns (other than those that are unchecked). 😊

**Comment by kcarcia** [comment] 2015-02-23 18:55
@JKinsman Can I add the issue mentioned in #1992 here?

**Comment by JKinsman** [comment] 2015-02-23 22:22
@kcarcia sure thing!  I know exactly what caused this.  It was a style for the mobile site I must not have scoped correctly.  I'll fix that when I submit the patch.  Whoops! :stuck_out_tongue:

**Comment by stowellm** [comment] 2015-02-24 19:20
Looking great, @JKinsman!  I have some more feedback, however :smile: 
- [ ] The text in the carousel has a shadow :scream:?  Isn't that bad?
- [ ] I'm not a fan of the gray background on the carousel
- [ ] The panes are switching pretty fast.  I understand we want them to rotate relatively quickly so the user sees "oh look, its a carousel!", but at the same time, it should be readable

**Closed** 2015-06-19 16:36 UTC
Labels: Mobile, UI
