### ISSUE TITLE
Histogram does not render correctly when using very large numbers

### ISSUE THREAD

**Issue by farxinu** [isenseDev/rSENSE#2434] opened 2016-06-27 15:28 UTC
While it's impossible to actually childproof anything, see [project 2437](https://isenseproject.org/projects/2437), where the students decided to upload numbers like 1*10^31. It doesn't visualize (which I'd expect anyway). Not sure if this actually qualifies as a bug, but I wanted to make you aware just in case.

**Comment by pat-son** [comment] 2016-06-27 20:46
Can you be a little more specific? Which data sets are not visualizing? I made a project with data in the 10^31 range and it visualizes, but there are some issues with Highcharts displaying numbers that big. Regardless, I can't replicate the bug if you don't tell me how.

In the future, please use the [template for reporting bugs](https://github.com/isenseDev/rSENSE/wiki#reporting-a-bug).

**Comment by pat-son** [comment] 2016-08-31 19:26
Never mind, what I thought was a display error is just how highcharts displays large numbers.
Closing this issue as I cannot reproduce the original cause.

**Closed by pat-son** 2016-08-31 19:26 UTC
Labels: Bug, Cannot Reproduce, Low Priority
