### ISSUE TITLE
Tools On All Vises Are... Off

### ISSUE THREAD

**Issue by kcarcia** [isenseDev/rSENSE#1953] opened 2015-01-27 03:41 UTC
**General description:** Tools on all vises are being all crazy. :( The image explains it all. It doesn't seem to be happening with saved vises, though.

**live/dev/localhost:** live
**iSENSE Version:** v5.12
**Logged in (Y or N):** Y
**Admin (Y or N):** N

**OS:** Macintosh
**Browser/Version:** Chrome 40.0.2214.91

**Steps to Reproduce:**
1. Go to a project with data.
2. Visualize that data.

**Associated Images:**
![screen shot 2015-01-26 at 10 06 42 pm](https://cloud.githubusercontent.com/assets/1798956/5913126/98953528-a5ac-11e4-9a47-c9b82ac77e58.png)

**Comment by kcarcia** [comment] 2015-01-27 03:43
@jaypoulz is this just me? :( I hope it is. I marked it as high priority because this is a release stopper.

**Comment by bdonald25** [comment] 2015-01-27 03:44
We were looking at it earlier. It looks like it is just that project.

**Comment by kcarcia** [comment] 2015-01-27 03:48
@bdonald25 Oh gosh... you're totally right. I didn't catch that. So weird. @jaypoulz should I close this?

**Comment by jaypoulz** [comment] 2015-01-27 03:48
It's just that project. Something you did caused something to become undefined, and that's messing up the vis. What you are describe is the symptom, not the bug itself. I need steps to reproduce this otherwise I can't do anything.

**Comment by jaypoulz** [comment] 2015-01-27 03:48
Up to you as to how we move forward on it. Clearly, a bug needs to be filed... but what is causing the problem :fearful:

**Comment by kcarcia** [comment] 2015-01-27 03:51
@jaypoulz I'll see if I can reproduce it...
![01c519c3163a7815561da5f6b1e594c2](https://cloud.githubusercontent.com/assets/1798956/5913198/ca265abc-a5ad-11e4-83d7-a36c2f12022a.jpg)

**Comment by kcarcia** [comment] 2015-01-30 00:20
@jaypoulz I cannot reproduce this. I tried creating a project just as I did before. Adding a number field, adding a data set, then adding a timestamp field, and another data set... Nothing. I tried looking at this project, and I just can't figure out what the issue is. I can't remember if there's anything else super specific that I did.

**Comment by jaypoulz** [comment] 2015-01-30 02:14
If we see it again and can reproduce, we'll try to fix this. For now I'm going to close this.

**Closed by jaypoulz** 2015-01-30 02:14 UTC
Labels: Bug, Cannot Reproduce, UI
