### ISSUE TITLE
Clicking "Create Project" causes the screen to freeze

### ISSUE THREAD

**Issue by isenseanon** [isenseDev/rSENSE#2288] opened 2015-11-03 21:17 UTC
**General description:** When I click create project my screen freezes.

**live/dev/localhost:** live
**iSENSE Version:** v7.4.1
**Logged in (Y or N):** Y
**Admin (Y or N):** N

**OS:** Macintosh
**Browser/Version:** Safari 9.0

**Steps to Reproduce:** I was trying to create a project.

3227

**Comment by bdonald25** [comment] 2015-11-04 00:43
@pat-son is going to email her since he is the only one with a mac. Neither of us could reproduce this.

**Comment by pat-son** [comment] 2015-11-05 08:56
I couldn't reproduce it either, and she never responded to my email. Is there a "user error" label for issues?

**Comment by asalani93** [comment] 2015-11-05 12:48
I don't think user error can make the screen freeze.

**Comment by bdonald25** [comment] 2015-11-05 17:00
I'm guessing they just clicked create without entering a name and didn't notice the huge error at the top. 

That's the only thing I can think of since we couldn't reproduce it. Pat used the same version of safari too.

If there is a bug we can't do anything about it without her responding.

**Comment by pat-son** [comment] 2015-11-05 18:12
@asalani93 I was referring to Bobby's theory that she just didn't name the project and was confused when clicking "create project" didn't do anything. Someone who is inexperienced with computers might naively assume that the screen was just frozen.

**Comment by bdonald25** [comment] 2015-12-28 01:52
She never emailed us back and we were never able to reproduce this so I am closing it.

**Closed by bdonald25** 2015-12-28 01:52 UTC
Labels: Cannot Reproduce
