### ISSUE TITLE
Downloaded descriptions

### ISSUE THREAD

**Issue by kcarcia** [isenseDev/rSENSE#1301] opened 2014-01-24 15:27 UTC
There are currently 2 issues with downloaded vises:

1. The description does not appear with the downloaded vis.

2. The x axis is  labeled uh, incorrectly. The X axis for this particular vis should be "Velocity" and you can see the letters buried in there. Also, here's the vis that was downloaded: http://isenseproject.org/visualizations/208
![screenshot from 2014-01-24 10 26 54](https://f.cloud.github.com/assets/1798956/1995888/0156292c-850c-11e3-9a63-620ccada8c01.png)

**Comment by kcarcia** [comment] 2015-01-21 17:29
@jdalphon @jaypoulz are we going to proceed with fixing the description now that we have Summernote?

**Comment by jaypoulz** [comment] 2015-01-21 18:00
@kcarcia It can't be reproduced, but @JKinsman found the cause when he was analyzing the regression code. He upcoming regression patch should address this.

**Comment by bdonald25** [comment] 2015-05-18 18:32
@jdalphon This is no longer a bug. Probably fixed by @jaypoulz 's vis patch.

**Closed** 2015-05-19 13:53 UTC
Labels: Bug, UI, Vis
