### ISSUE TITLE
when lots of individual objects to be graphed, key overwhelms visualization

### ISSUE THREAD

**Issue by fgmart** [isenseDev/rSENSE#2176] opened 2015-06-08 16:59 UTC
See below.

Maybe solution is to put the key in a scrolling window after it gets too big?

![foo](https://cloud.githubusercontent.com/assets/1038856/8040405/47ee68d4-0dde-11e5-9c14-0f412a5eadda.png)

**Comment by bdonald25** [comment] 2015-06-08 17:31
Duplicate of issue #2141.

**Closed by bdonald25** 2015-06-08 17:31 UTC
