### ISSUE TITLE
Add "Next 100 button" at bottom of list of data sets on project show page

### ISSUE THREAD

**Issue by theyoyojo** [isenseDev/rSENSE#2757] opened 2017-11-14 20:44 UTC
May also add number to display option

Could be done with javascript instead to prevent the page from reloading every time, but this way the look matches the pagination for the projects page

**Comment by fgmart** [comment] 2017-11-15 21:12
Yes, the idea here is to continue grabbing the entire list of data sets, and the contents of those data sets when the page loads, but to not show all of them in the browser page.

All data sets will be implicitly selected on page load, so if the user clicks Visualize, all will be visualized.

Instead of pagination, I would like a button at the bottom that is something like "Display next 100 data sets" (up to 100, if there are fewer than this remaining, it should show [e.g.] "Display remaining 53 data sets").

This would speed up browser rendering of pages with many data sets, hopefully significantly.

This project has >3000 data sets, for testing: http://isenseproject.org/projects/3332

**Comment by doug-salvati** [comment] 2017-11-20 16:28
duplicate of #2733

**Comment by doug-salvati** [comment] 2017-12-01 17:40
PASSED testing on Chrome 62.0.3202.75 (linux).
Works as described

**Comment by Dayyvid** [comment] 2017-12-01 17:56
PASSED testing on Chrome 62.0.3202.94 (windows).

**Comment by mck529** [comment] 2017-12-01 19:16
PASSED testing on Chrome 62.0.3202.94 (Windows 10 x64).

**Closed** 2017-12-01 19:34 UTC
