### ISSUE TITLE
last login information is not recorded properly

### ISSUE THREAD

**Issue by fgmart** [isenseDev/rSENSE#2808] opened 2018-03-02 00:06 UTC
Everyone's showing up as Aug 16, 2013. (e.g. per below)

![isense-users](https://user-images.githubusercontent.com/1038856/36876572-a379f508-1d83-11e8-9d84-8c55ead90f8f.png)

**Comment by doug-salvati** [comment] 2018-03-02 17:32
Duplicate of #2717

**Closed by doug-salvati** 2018-03-02 17:32 UTC
Labels: Bug
