### ISSUE TITLE
Linear best fit produces unhelpful errors

### ISSUE THREAD

**Issue by isenseanon** [isenseDev/rSENSE#1893] opened 2014-12-15 18:56 UTC
**General description:** Project 805:  Trying to generate a line of best fit for Kristen Laferriere's data set, but get an error "cannot generate line of best fit for this data".  Using x = Normal Force, y = either frictional force.
Thanks,

**live/dev/localhost:** live
**iSENSE Version:** v5.12
**Logged in (Y or N):** Y
**Admin (Y or N):** N

**OS:** Windows
**Browser/Version:** Internet Explorer 11.0

**Steps to Reproduce:** trying to generate a LOBF

338

**Comment by jaypoulz** [comment] 2015-01-09 16:59
TESTERS:
A good test for this bug would be to make a project for this particular data set, and see if linear regressions are still undefined.

**Comment by JKinsman** [comment] 2015-01-23 18:05
PASSED testing on Safari 8.0.2 (Mac OSX 10.10).

**Comment by asalani93** [comment] 2015-01-26 17:25
PASSED testing on Chrome 39.0.2171.71 (Ubuntu 14.04.1).

**Comment by kcarcia** [comment] 2015-01-27 03:16
PASSED testing on Chrome 40.0.2214.91 (mac).

**Comment by stowellm** [comment] 2015-01-29 16:36
PASSED testing on Chrome 40.0.2214.93 (OSX Yosemite 10.10.1).
To better the description of the error that was being produced on live (that seems to be fixed now): put normal force on the X axis, and *both* of the frictional forces on the Y axis when drawing a regression.

**Comment by asalani93** [comment] 2015-01-30 17:20
PASSED testing on Chrome 39.0.2171.71 (UUBBUUNNTTUU 1144..0044).

**Comment by bdonald25** [comment] 2015-01-30 18:01
PASSED testing on Chrome 41.0.2272.35 (mac).

**Comment by stowellm** [comment] 2015-01-30 18:44
PASSED testing on Chrome 40.0.2214.93 (OSX).

**Comment by JKinsman** [comment] 2015-01-30 18:49
PASSED testing on Safari 8.0.3 (Mac OSX 10.10.2).

**Closed** 2015-01-30 19:05 UTC
Labels: Bug, In Testing, Vis
