### ISSUE TITLE
"Likes" overflow on the project page

### ISSUE THREAD

**Issue by bdonald25** [isenseDev/rSENSE#1927] opened 2015-01-21 01:12 UTC
**General description:** "Likes" overflow on project page.

**live/dev/localhost:** live
**iSENSE Version:** v5.12
**Logged in (Y or N):** Y
**Admin (Y or N):** N

**OS:** Windows
**Browser/Version:** Chrome 39.0.2171.99

**Steps to Reproduce:** On the Projects page. Chrome is snapped to only fill half of my screen.

![20150120_200651](https://cloud.githubusercontent.com/assets/4121924/5829484/e11078a6-a0e0-11e4-9806-eec4661c56fb.jpg)

393

**Comment by kcarcia** [comment] 2015-05-01 03:41
@jdalphon I know you provided me the code for this, but it looks like the text overflows over the grey boxes, and I simply didn't have time to fool around with this to get it to work, so I've assigned this to you since you're doing a UI overhaul.

**Comment by asalani93** [comment] 2015-06-24 14:10
Duplicate of #2169

**Closed by asalani93** 2015-06-24 14:10 UTC
Labels: UI
