### ISSUE TITLE
User Submitted Issue

### ISSUE THREAD

**Issue by isenseanon** [isenseDev/rSENSE#1931] opened 2015-01-21 22:34 UTC
**General description:** I'm trying to edit name of new project (#823) but it won't let me change it (blinks red)

**live/dev/localhost:** live
**iSENSE Version:** v5.12
**Logged in (Y or N):** Y
**Admin (Y or N):** N

**OS:** Windows
**Browser/Version:** Internet Explorer 11.0

**Steps to Reproduce:** edit project name/save changes

338

**Comment by stowellm** [comment] 2015-01-22 13:29
Duplicate of #1669

**Comment by jaypoulz** [comment] 2015-01-22 16:50
Closing as duplicate

**Closed by jaypoulz** 2015-01-22 16:50 UTC
