### ISSUE TITLE
IE 11 Can't Change Project Title

### ISSUE THREAD

**Issue by tylerpuleo** [isenseDev/rSENSE#1823] opened 2014-10-17 15:08 UTC
**General description:**
Can't change project title of newly created project when using IE 11 on Windows 8.1

**live/dev/localhost:**
dev

**iSENSE Version:**
v5.8-91-ge3e1326 

**Logged in (Y or N):**
Y

**Admin (Y or N):**
N

**OS:**
Windows 8.1

**Browser/Version:**
IE 11

**Steps to Reproduce:**
Make a new project. Try to change the name after it has been created

**Associated Image(s):**

**Comment by kcarcia** [comment] 2015-01-21 17:35
Closing this b/c it is a duplicate of #1669

**Closed by kcarcia** 2015-01-21 17:35 UTC
Labels: Bug, Low Priority
